export const TYPES = [
  'normal',
  'fire',
  'water',
  'grass',
  'electric',
  'ice',
  'fighting',
  'poison',
  'ground',
  'flying',
  'psychic',
  'bug',
  'rock',
  'ghost',
  'dragon',
  'dark',
  'steel',
  'fairy',
];

export const typeTranslations: Record<string, { ja: string; en: string }> = {
  normal: { ja: 'ノーマル', en: 'Normal' },
  fire: { ja: 'ほのお', en: 'Fire' },
  water: { ja: 'みず', en: 'Water' },
  grass: { ja: 'くさ', en: 'Grass' },
  electric: { ja: 'でんき', en: 'Electric' },
  ice: { ja: 'こおり', en: 'Ice' },
  fighting: { ja: 'かくとう', en: 'Fighting' },
  poison: { ja: 'どく', en: 'Poison' },
  ground: { ja: 'じめん', en: 'Ground' },
  flying: { ja: 'ひこう', en: 'Flying' },
  psychic: { ja: 'エスパー', en: 'Psychic' },
  bug: { ja: 'むし', en: 'Bug' },
  rock: { ja: 'いわ', en: 'Rock' },
  ghost: { ja: 'ゴースト', en: 'Ghost' },
  dragon: { ja: 'ドラゴン', en: 'Dragon' },
  dark: { ja: 'あく', en: 'Dark' },
  steel: { ja: 'はがね', en: 'Steel' },
  fairy: { ja: 'フェアリー', en: 'Fairy' },
};

export const typeColors: Record<string, string> = {
  normal: 'bg-slate-400 text-slate-900',
  fire: 'bg-red-500 text-white',
  water: 'bg-blue-500 text-white',
  grass: 'bg-green-500 text-white',
  electric: 'bg-yellow-400 text-slate-900',
  ice: 'bg-cyan-400 text-slate-900',
  fighting: 'bg-amber-700 text-white',
  poison: 'bg-purple-500 text-white',
  ground: 'bg-amber-600 text-white',
  flying: 'bg-indigo-300 text-slate-900',
  psychic: 'bg-pink-500 text-white',
  bug: 'bg-lime-500 text-slate-900',
  rock: 'bg-yellow-600 text-white',
  ghost: 'bg-violet-700 text-white',
  dragon: 'bg-indigo-700 text-white',
  dark: 'bg-slate-800 text-white',
  steel: 'bg-zinc-500 text-white',
  fairy: 'bg-rose-400 text-slate-900',
};

export const megaStoneMap: Record<string, { ja: string; en: string }> = {
  メガフシギバナ: { ja: 'フシギバナイト', en: 'Venusaurite' },
  メガリザードンX: { ja: 'リザードナイトX', en: 'Charizardite X' },
  メガリザードンY: { ja: 'リザードナイトY', en: 'Charizardite Y' },
  メガカメックス: { ja: 'カメックスナイト', en: 'Blastoisinite' },
  メガスピアー: { ja: 'スピアーナイト', en: 'Beedrillite' },
  メガピジョット: { ja: 'ピジョットナイト', en: 'Pidgeotite' },
  メガフーディン: { ja: 'フーディナイト', en: 'Alakazite' },
  メガヤドラン: { ja: 'ヤドランナイト', en: 'Slowbronite' },
  メガゲンガー: { ja: 'ゲンガナイト', en: 'Gengarite' },
  メガガルーラ: { ja: 'ガルーラナイト', en: 'Kangaskhanite' },
  メガカイロス: { ja: 'カイロスナイト', en: 'Pinsirite' },
  メガギャラドス: { ja: 'ギャラドスナイト', en: 'Gyaradosite' },
  メガプテラ: { ja: 'プテラナイト', en: 'Aerodactylite' },
  メガデンリュウ: { ja: 'デンリュウナイト', en: 'Ampharosite' },
  メガハッサム: { ja: 'ハッサムナイト', en: 'Scizorite' },
  メガヘラクロス: { ja: 'ヘラクロスナイト', en: 'Heracronite' },
  メガヘルガー: { ja: 'ヘルガナイト', en: 'Houndoominite' },
  メガバンギラス: { ja: 'バンギラスナイト', en: 'Tyranitarite' },
  メガジュカイン: { ja: 'ジュカインナイト', en: 'Sceptilite' },
  メガバシャーモ: { ja: 'バシャーモナイト', en: 'Blazikenite' },
  メガラグラージ: { ja: 'ラグラージナイト', en: 'Swampertite' },
  メガサーナイト: { ja: 'サーナイトナイト', en: 'Gardevoirite' },
  メガヤミラミ: { ja: 'ヤミラミナイト', en: 'Sablenite' },
  メガクチート: { ja: 'クチートナイト', en: 'Mawilite' },
  メガボスゴドラ: { ja: 'ボスゴドラナイト', en: 'Aggronite' },
  メガチャーレム: { ja: 'チャーレムナイト', en: 'Medichamite' },
  メガライボルト: { ja: 'ライボルトナイト', en: 'Manectrite' },
  メガサメハダー: { ja: 'サメハダナイト', en: 'Sharpedonite' },
  メガバクーダ: { ja: 'バクーダナイト', en: 'Cameruptite' },
  メガチルタリス: { ja: 'チルタリスナイト', en: 'Altarianite' },
  メガジュペッタ: { ja: 'ジュペッタナイト', en: 'Banettite' },
  メガアブソル: { ja: 'アブソルナイト', en: 'Absolite' },
  メガオニゴーリ: { ja: 'オニゴーリナイト', en: 'Glalitite' },
  メガボーマンダ: { ja: 'ボーマンダナイト', en: 'Salamencite' },
  メガメタグロス: { ja: 'メタグロスナイト', en: 'Metagrossite' },
  メガレックウザ: {
    ja: 'なし (画竜点睛が必要)',
    en: 'None (Dragon Ascent required)',
  },
  メガラティアス: { ja: 'ラティアスナイト', en: 'Latiasite' },
  メガラティオス: { ja: 'ラティオスナイト', en: 'Latiosite' },
  メガディアンシー: { ja: 'ディアンシナイト', en: 'Diancite' },
  メガエルレイド: { ja: 'エルレイドナイト', en: 'Galladite' },
  メガタブンネ: { ja: 'タブンネナイト', en: 'Audinite' },
  メガミミロップ: { ja: 'ミミロップナイト', en: 'Lopunnite' },
  メガハガネール: { ja: 'ハガネールナイト', en: 'Steelixite' },
  メガユキノオー: { ja: 'ユキノオナイト', en: 'Abomasnowite' },
};
